# Generated by Django 4.1.3 on 2022-11-02 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('yil', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('t_yil', models.PositiveSmallIntegerField()),
                ('davlat', models.CharField(max_length=20)),
                ('jins', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('davomiylik', models.DurationField(null=True)),
                ('janr', models.CharField(blank=True, max_length=10)),
                ('mp3_fayl', models.URLField(null=True)),
                ('albom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.albom')),
            ],
        ),
        migrations.AddField(
            model_name='albom',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.singer'),
        ),
    ]
