# Generated by Django 4.1.3 on 2022-11-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='jins',
            field=models.CharField(max_length=10),
        ),
    ]
