# Generated by Django 4.1.3 on 2022-11-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_singer_jins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='jins',
            field=models.CharField(max_length=6),
        ),
    ]
